#ifndef _FUNCONFIG_H
#define _FUNCONFIG_H

#define FUNCONF_USE_DEBUGPRINTF 1
#define FUNCONF_ENABLE_HPE 1
#define FUNCONF_SYSTICK_USE_HCLCK 1
#define FUNCONF_DEBUG_HARDFAULT   1
#define FUNCONF_USE_CLK_SEC 0


#endif

